export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { query, data } = req.body;
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
      return res.status(500).json({ error: 'GEMINI_API_KEY is not configured on the server.' });
    }

    const r = await fetch(
      "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=" + apiKey,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: `
You are Infinity AI, an intelligent assistant built into OpenDots.
Always respond in a single <div>. Keep it concise.
User query: ${query}
Data: ${JSON.stringify(data || {})}
                    `,
                },
              ],
            },
          ],
        }),
      },
    );

    const j = await r.json();

    if (!r.ok) {
      console.error("Gemini API Error:", j);
      return res.status(r.status).json({ error: j.error?.message || "Gemini API returned an error." });
    }

    const reply = j.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!reply) {
      return res.status(500).json({ error: "No response generated by the AI." });
    }

    res.status(200).json({ reply });
  } catch (err) {
    console.error("Server Error:", err);
    res.status(500).json({ error: err.message });
  }
}

